train:
  waveforms:
    files:
      - train.wav
    channels:
      - [0]
    lenghts:
      - 92747
    samplerate: 16000
  supervision:
    - train_spk1_8320_13600: # we can add label type eg speech ?
        spk_id: spk1
        start: 8320
        stop: 13600
    - train_spk1_21120_29280:
        spk_id: spk1
        start: 21120
        stop: 29280
    - train_spk2_37600_59200:
        spk_id: spk2
        start: 37600
        stop: 59200

