# Basic parameters
sample_rate: 16000

# Data files
data_folder: !PLACEHOLDER
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Neural Parameters
N_epochs: 4
N_batch: 2
lr: 0.0004

train_loader: !speechbrain.data_io.data_io.DataLoaderFactory
    &loader
    csv_file: !ref <csv_train>
    batch_size: !ref <N_batch>
    csv_read: [wav, spk_id]
    output_folder: !ref <output_folder>
    replacements:
        $data_folder: !ref <data_folder>

valid_loader: !speechbrain.data_io.data_io.DataLoaderFactory
    <<: *loader
    csv_file: !ref <csv_valid>

test_loader: !speechbrain.data_io.data_io.DataLoaderFactory
    <<: *loader
    csv_file: !ref <csv_test>
    batch_size: 1

compute_features: !speechbrain.lobes.features.mfcc.MFCC

mean_var_norm: !speechbrain.processing.features.InputNormalization
    norm_type: global

linear1: !speechbrain.nnet.linear.Linear
    n_neurons: 1024
    bias: False

activation: !torch.nn.LeakyReLU

linear2: !speechbrain.nnet.linear.Linear
    n_neurons: 2
    bias: False

softmax: !speechbrain.nnet.activations.Softmax
    apply_log: True

compute_cost: !speechbrain.nnet.losses.ComputeCost
    cost_type: nll

compute_error: !speechbrain.nnet.losses.ComputeCost
    cost_type: error

optimizer: !speechbrain.nnet.optimizers.Optimize
    optimizer_type: adam
    learning_rate: !ref <lr>
