# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Data files
data_folder: !PLACEHOLDER
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Neural Parameters
N_epochs: 25
N_batch: 2
lr: 0.0004

train_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <N_batch>
    csv_read: [wav, ali]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

valid_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <N_batch>
    csv_read: [wav, ali]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

test_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    csv_read: [wav, ali]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

linear1: !new:speechbrain.nnet.Linear
    input_size: 660
    n_neurons: 1024
    bias: False

linear2: !new:speechbrain.nnet.Linear
    input_size: 1024
    n_neurons: 43
    bias: False

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

hparams:
    linear1: !ref <linear1>
    linear2: !ref <linear2>
    compute_features: !new:speechbrain.lobes.MFCC
    mean_var_norm: !new:speechbrain.processing.InputNormalization
        norm_type: global
    activation: !new:torch.nn.LeakyReLU
    softmax: !new:speechbrain.nnet.Softmax
        apply_log: True
    compute_cost: !name:speechbrain.nnet.nll_loss
    error_stats: !name:speechbrain.MetricStats
        metric: !name:speechbrain.nnet.classification_error
            reduction: batch
