seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
data_folder: /localscratch/voxceleb/voxceleb1/
output_folder: libriparty_experiment
save_folder: !ref <output_folder>/save/

xvector_file: https://www.dropbox.com/s/skfz2sme5nw7jji/xvector_model.ckpt?dl=1

csv_train: !ref <save_folder>/train.csv
csv_test: !ref <save_folder>/eval.csv


train_iterations: 50
train_loader_batch_size: 100
batch_size: 10
lr: 0.001
wd: 0.00001
grad_max_norm: 5.0
device: 'cuda:0'

# Feature parameters
n_mels: 24
left_frames: 0
right_frames: 0
deltas: False

# RNN parameters
rnn_hidden_size: 512
rnn_layers: 1
rnn_dropout: 0.2

# Linear parameters
output_size: 256
activation: !new:torch.nn.ReLU


# Functions
compute_features: !new:speechbrain.lobes.features.fbank.Fbank
    n_mels: !ref <n_mels>
    left_frames: !ref <left_frames>
    right_frames: !ref <right_frames>
    deltas: !ref <deltas>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

mean_var_norm_xvect: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    std_norm: False

xvector_model: !new:speechbrain.lobes.models.Xvector.Xvector
    activation: !name:torch.nn.LeakyReLU
    device: !ref <device>
    tdnn_blocks: 5
    tdnn_channels: [512, 512, 512, 512, 1500]
    tdnn_kernel_sizes: [5, 3, 3, 1, 1]
    tdnn_dilations: [1, 2, 3, 1, 1]
    lin_neurons: 512


rnn_model: !new:speechbrain.nnet.RNN.GRU
    hidden_size: !ref <rnn_hidden_size>
    num_layers: !ref <rnn_layers>
    dropout: !ref <rnn_dropout>
    return_hidden: True

first_linear_layer: !new:speechbrain.nnet.linear.Linear
    n_neurons: !ref <rnn_hidden_size>
output_linear_layer: !new:speechbrain.nnet.linear.Linear
    n_neurons: !ref <output_size>

# compute_cost: !new:speechbrain.nnet.losses.weighted_mse_loss

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>
    weight_decay: !ref <wd>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <train_iterations>

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <train_loader_batch_size>
    csv_read: [wav, spk_id]
    sentence_sorting: random
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/
