# ################################
# Model: ConvTasnet for source separation
# Data : WSJ0-2mix-8k-min
# Author: Cem Subakan
# ################################

# Basic parameters
# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]
use_tensorboard: True
tensorboard_logs: runs/1-newexperiment
output_folder: !ref results/conv_tasnet/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Neural Parameters
N_epochs: 100
N_batch: 2
lr: 0.0002
train_onthefly: False
loss_fn: 'sisnr'
progressbar: True

# The path for wsj0-mix data
# e.g. '/network/tmp1/subakany/wsj0-mix-speechbrain-2speakers/'
wsj0mixpath: !PLACEHOLDER

# The path for the folder which contains wsj0 folder.
# This is used only if the wsj0-mix is not already ready to be used.
# e.g. '/network/tmp1/subakany/wsj0-mix/'
wsj0path: !PLACEHOLDER


tr_csv: 'wsj_tr.csv'
cv_csv: 'wsj_cv.csv'
tt_csv: 'wsj_tt.csv'

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <tr_csv>
    batch_size: !ref <N_batch>
    sentence_sorting: ascending
    csv_read: [mix_wav, s1_wav, s2_wav]

val_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <cv_csv>
    batch_size: !ref <N_batch>
    sentence_sorting: ascending
    csv_read: [mix_wav, s1_wav, s2_wav]

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <tt_csv>
    batch_size: !ref <N_batch>
    sentence_sorting: ascending
    csv_read: [mix_wav, s1_wav, s2_wav]

augmentation: !new:speechbrain.lobes.augment.tdsa.TimeDomainSpecAugment
    sample_rate: 8000
    speeds: [95, 100, 105]


MaskNet: !new:speechbrain.lobes.models.conv_tasnet.MaskNet
    N: 256
    B: 256
    H: 512
    P: 3
    X: 8
    R: 4
    C: 2
    norm_type: 'gLN'
    causal: False
    mask_nonlinear: 'relu'

Encoder: !new:speechbrain.lobes.models.conv_tasnet.Encoder
    L: 21
    N: 256

Decoder: !new:speechbrain.lobes.models.conv_tasnet.Decoder
    # N: 256
    L: 20

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <N_epochs>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        encoder: !ref <Encoder>
        decoder: !ref <Decoder>
        masknet: !ref <MaskNet>
        optimizer: !ref <optimizer>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
    summary_fns:
        SISNR: !name:speechbrain.utils.train_logger.summarize_error_rate
