# ################################
# Model: 2D FCN SE baseline
# Authors: Szu-Wei, Fu 2020
# ################################


# Seed needs to be set at top of yaml, before objects with parameters are made
seed: !PLACEHOLDER  # e.g, 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

data_folder: !PLACEHOLDER
test_clean_folder: !ref <data_folder>/clean_testset_wav_16k/

output_folder: !ref ./results/FCN/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
enhanced_folder: !ref <output_folder>/FCN_enhanced

# Basic parameters
use_tensorboard: True
tensorboard_logs: !ref <output_folder>/logs

# FFT paremeters
Sample_rate: 16000
Win_length: 32
Hop_length: 16
N_fft: 512
window_type: hamming

# Data files
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/valid.csv
csv_test: !ref <data_folder>/test.csv

# Training Parameters
number_of_epochs: 50
N_batch: 8
lr: 0.001
device: 'cuda:0'

# Neural parameters
kernel_size: (7,7)
base_channels: 64

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <N_batch>
    csv_read: [noisy_wav, clean_wav]
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    select_n_sentences: 20

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: 1
    csv_read: [noisy_wav, clean_wav]
    replacements:
        $data_folder: !ref <data_folder>

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    batch_size: 1
    csv_read: [noisy_wav, clean_wav]
    replacements:
        $data_folder: !ref <data_folder>

epoch_counter: !new:speechbrain.EpochCounter
    limit: !ref <number_of_epochs>

modules:
    use_tensorboard: !ref <use_tensorboard>
    train_logger: !new:speechbrain.FileTrainLogger
        save_file: !ref <train_log>
    compute_STFT: !new:speechbrain.processing.STFT
        sample_rate: !ref <Sample_rate>
        win_length: !ref <Win_length>
        hop_length: !ref <Hop_length>
        n_fft: !ref <N_fft>
        window_type: !ref <window_type>
    compute_ISTFT: !new:speechbrain.processing.ISTFT
        sample_rate: !ref <Sample_rate>
        win_length: !ref <Win_length>
        hop_length: !ref <Hop_length>
        window_type: !ref <window_type>
    mean_var_norm: !new:speechbrain.processing.InputNormalization
        norm_type: sentence
    conv1: !name:speechbrain.nnet.Conv2d
        out_channels: !ref <base_channels>
        kernel_size: !ref <kernel_size>
    conv2: !name:speechbrain.nnet.CNN.Conv2d
        out_channels: !ref <base_channels> // 2
        kernel_size: !ref <kernel_size>
    conv3: !name:speechbrain.nnet.CNN.Conv2d
        out_channels: !ref <base_channels> // 2
        kernel_size: !ref <kernel_size>
    conv4: !name:speechbrain.nnet.CNN.Conv2d
        out_channels: !ref <base_channels> // 4
        kernel_size: !ref <kernel_size>
    conv5: !name:speechbrain.nnet.CNN.Conv2d
        out_channels: !ref <base_channels> // 4
        kernel_size: !ref <kernel_size>
    conv6: !name:speechbrain.nnet.CNN.Conv2d
        out_channels: !ref <base_channels> // 8
        kernel_size: !ref <kernel_size>
    conv7: !name:speechbrain.nnet.CNN.Conv2d
        out_channels: !ref <base_channels> // 16
        kernel_size: !ref <kernel_size>
    conv8: !name:speechbrain.nnet.CNN.Conv2d
        out_channels: 1
        kernel_size: !ref <kernel_size>
    activation: !new:torch.nn.LeakyReLU
        negative_slope: 0.01
    activation_sigmoid: !new:torch.nn.Sigmoid
    BN: !new:speechbrain.nnet.BatchNorm2d
    model: !new:speechbrain.nnet.Sequential
        - !ref <conv1>
        - !ref <BN>
        - !ref <activation>
        - !ref <conv2>
        - !ref <BN>
        - !ref <activation>
        - !ref <conv3>
        - !ref <BN>
        - !ref <activation>
        - !ref <conv4>
        - !ref <BN>
        - !ref <activation>
        - !ref <conv5>
        - !ref <BN>
        - !ref <activation>
        - !ref <conv6>
        - !ref <BN>
        - !ref <activation>
        - !ref <conv7>
        - !ref <BN>
        - !ref <activation>
        - !ref <conv8>
        - !ref <BN>
        - !ref <activation_sigmoid>
    compute_cost: !name:speechbrain.nnet.mse_loss
    optimizer: !new:torch.optim.Adam
        params: !apply:speechbrain.collect_params
            - !ref <modules.model>
        learning_rate: !ref <lr>
    checkpointer: !new:speechbrain.Checkpointer
        checkpoints_dir: !ref <save_folder>
        recoverables:
            model: !ref <modules.model>
            optimizer: !ref <modules.optimizer>
            counter: !ref <epoch_counter>
