# ################################
# Model: 1-D causal CNNTransformer model
# Authors: Chien-Feng Liao
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

data_folder: !PLACEHOLDER
test_clean_folder: !ref <data_folder>/clean_testset_wav_16k/

output_folder: !ref ./results/transformer/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
enhanced_folder: !ref <output_folder>/BLSTM_enhanced

# Basic parameters
use_tensorboard: True
tensorboard_logs: !ref ./results/BLSTM/<seed>/logs/

# FFT paremeters
Sample_rate: 16000
Win_length: 32
Hop_length: 16
N_fft: 512
window_fn: !name:torch.hamming_window

# Data files
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/valid.csv
csv_test: !ref <data_folder>/test.csv

# Training Parameters
number_of_epochs: 50
N_batch: 4
lr: 0.0001
device: 'cuda:0'

# Model Parameters
drop_rate: 0.1
num_blocks: 8
intermediate_size: 512
num_heads: 8
causal: False
kernel_size: 3
base_channels: 1024
padding_type: same
activation: !name:torch.nn.LeakyReLU
output_activation: !name:torch.nn.ReLU

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <N_batch>
    csv_read: [noisy_wav, clean_wav]
    sentence_sorting: ascending
    output_folder: !ref <output_folder>

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: 4
    csv_read: [noisy_wav, clean_wav]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    batch_size: 1
    csv_read: [noisy_wav, clean_wav]
    replacements:
        $data_folder: !ref <data_folder>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

embedding_module: !new:speechbrain.nnet.Sequential
    - [null, null, !ref <N_fft> // 2 + 1]
    - !name:speechbrain.nnet.Conv1d
      out_channels: !ref <base_channels>
      kernel_size: !ref <kernel_size>
      padding: !ref <padding_type>
    - !name:speechbrain.nnet.LayerNorm
    - !new:torch.nn.LeakyReLU
    - !name:speechbrain.nnet.Conv1d
      out_channels: !ref <base_channels> // 2
      kernel_size: !ref <kernel_size>
      padding: !ref <padding_type>
    - !name:speechbrain.nnet.LayerNorm
    - !new:torch.nn.LeakyReLU
    - !name:speechbrain.nnet.Conv1d
      out_channels: !ref <base_channels> // 8
      kernel_size: !ref <kernel_size>
      padding: !ref <padding_type>
    - !name:speechbrain.nnet.LayerNorm
    - !new:torch.nn.LeakyReLU
    - !name:speechbrain.nnet.Conv1d
      out_channels: !ref <base_channels> // 4
      kernel_size: !ref <kernel_size>
      padding: !ref <padding_type>
    - !name:speechbrain.nnet.LayerNorm
    - !new:torch.nn.LeakyReLU

model: !new:speechbrain.lobes.CNNTransformerSE
    output_size: !ref <N_fft> // 2 + 1
    input_size: !ref <N_fft> // 2
    output_activation: !ref <output_activation>
    activation: !ref <activation>
    dropout: !ref <drop_rate>
    num_layers: !ref <num_blocks>
    d_ffn: !ref <intermediate_size>
    nhead: !ref <num_heads>
    causal: !ref <causal>
    custom_emb_module: !ref <embedding_module>

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

checkpointer: !new:speechbrain.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        counter: !ref <epoch_counter>

hparams:
    use_tensorboard: !ref <use_tensorboard>
    epoch_counter: !ref <epoch_counter>
    model: !ref <model>
    enhanced_folder: !ref <enhanced_folder>
    compute_cost: !name:speechbrain.nnet.mse_loss
    compute_STFT: !new:speechbrain.processing.features.STFT
        sample_rate: !ref <Sample_rate>
        win_length: !ref <Win_length>
        hop_length: !ref <Hop_length>
        n_fft: !ref <N_fft>
        window_fn: !ref <window_fn>
    compute_ISTFT: !new:speechbrain.processing.features.ISTFT
        sample_rate: !ref <Sample_rate>
        win_length: !ref <Win_length>
        hop_length: !ref <Hop_length>
        window_fn: !ref <window_fn>
    mean_var_norm: !new:speechbrain.processing.features.InputNormalization
        norm_type: sentence
    train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
        save_file: !ref <train_log>
