# Basic parameters
# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
use_tensorboard: False
tensorboard_logs: runs

# Data files
data_folder: !PLACEHOLDER
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Neural Parameters
N_epochs: 100
N_batch: 2
lr: 0.004

train_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <N_batch>
    csv_read: [wav]
    sentence_sorting: random
    replacements:
        $data_folder: !ref <data_folder>

valid_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <N_batch>
    csv_read: [wav]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

test_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    csv_read: [wav]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

linear1: !new:speechbrain.nnet.Linear
    input_size: 180
    n_neurons: 128
    bias: False

linear2: !new:speechbrain.nnet.Linear
    input_size: 128
    n_neurons: 180
    bias: False

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

hparams:
    use_tensorboard: !ref <use_tensorboard>
    compute_features: !new:speechbrain.lobes.MFCC
        left_frames: 1
        right_frames: 1
    mean_var_norm: !new:speechbrain.processing.InputNormalization
        norm_type: global
    linear1: !ref <linear1>
    linear2: !ref <linear2>
    activation: !new:torch.nn.LeakyReLU
    compute_cost: !name:speechbrain.nnet.mse_loss
    loss_tracker: !name:speechbrain.MetricStats
        metric: !name:speechbrain.nnet.mse_loss
            reduction: batch
