# ################################
# Model: Baseline 1-D CNN model with log1p mapping
# Authors: Chien-Feng Liao
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: !PLACEHOLDER  # e.g, 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Basic parameters
data_folder: !PLACEHOLDER
output_folder: !ref results/baseline_log1p/<seed>
train_log: !ref <output_folder>/train_log.txt
enhanced_folder: !ref <output_folder>/enhanced/

use_tensorboard: True
tensorboard_logs: !ref results/logs/baseline_log1p/<seed>

# Data files
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/test.csv

# Neural Parameters
N_epochs: 100
N_batch: 8
lr: 0.0002
device: cuda:0

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
  csv_file: !ref <csv_train>
  batch_size: !ref <N_batch>
  csv_read: [noisy_wav, clean_wav]
  cache: False
  num_workers: 1

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
  csv_file: !ref <csv_valid>
  batch_size: !ref <N_batch>
  csv_read: [noisy_wav, clean_wav]

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
  limit: !ref <N_epochs>

compute_stft: !new:speechbrain.processing.features.STFT
  sample_rate: 16000
  win_length: 32
  hop_length: 16
  n_fft: 512

compute_istft: !new:speechbrain.processing.features.ISTFT
  sample_rate: 16000
  win_length: 32
  hop_length: 16

conv1: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: 2048
  kernel_size: 7

conv2: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: 1024
  kernel_size: 7

conv3: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: 512
  kernel_size: 7

conv4: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: 256
  kernel_size: 7

conv5: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: 128
  kernel_size: 7

conv6: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: 256
  kernel_size: 7

conv7: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: 512
  kernel_size: 7

linear: !new:speechbrain.nnet.linear.Linear
  n_neurons: 257
  bias: False

activation: !new:torch.nn.LeakyReLU
output_activation: !new:torch.nn.ReLU

model: !new:speechbrain.nnet.containers.Sequential
  [
    !ref <conv1>,
    !ref <activation>,
    !ref <conv2>,
    !ref <activation>,
    !ref <conv3>,
    !ref <activation>,
    !ref <conv4>,
    !ref <activation>,
    !ref <conv5>,
    !ref <activation>,
    !ref <conv6>,
    !ref <activation>,
    !ref <conv7>,
    !ref <activation>,
    !ref <linear>,
    !ref <output_activation>
  ]

compute_cost: !name:speechbrain.nnet.losses.mse_loss

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
  learning_rate: !ref <lr>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: !ref <output_folder>/save
  recoverables:
    optimizer: !ref <optimizer>
    counter: !ref <epoch_counter>
    model: !ref <model>
