# ################################
# Model: Speaker Verification Baseline
# Authors: Hwidong Na 2020
# ################################

seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
voxceleb_source: /network/datasets/restricted/voxceleb_users/voxceleb/voxceleb1
data_folder: /localscratch/voxceleb1
output_folder: results/voxceleb1_2/speaker_verification_ecapa_tdnn
save_folder: !ref <output_folder>/save/
device: 'cuda:0'

# Pretrain from web (as an alternative specify a file)
embedding_file:
    https://www.dropbox.com/s/hqbxfcft0ay9qdy/embedding_model.ckpt?dl=1 # vox1+2

# csv files
csv_enrol: !ref <save_folder>/enrol.csv
csv_test: !ref <save_folder>/test.csv

batch_size: 32

# Feature parameters
n_mels: 80
left_frames: 0
right_frames: 0
deltas: False

# Functions
compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>
    left_frames: !ref <left_frames>
    right_frames: !ref <right_frames>
    deltas: !ref <deltas>

embedding_model: !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN
    input_size: !ref <n_mels>
    channels: [512, 512, 512, 512, 1536]
    kernel_sizes: [5, 3, 3, 3, 1]
    dilations: [1, 2, 3, 4, 1]
    attention_channels: 128
    lin_neurons: 192

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

mean_var_norm_emb: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    std_norm: False

enrol_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_enrol>
    batch_size: !ref <batch_size>
    csv_read: [wav]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    batch_size: !ref <batch_size>
    csv_read: [wav]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/
