data_folder: !PLACEHOLDER  # e.g. /path/to/TIMIT
predictions_file: !ref <output_folder>/predictions.csv
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>/save
ckpts_to_keep: 1
sample_rate: 16000
seed: !PLACEHOLDER  # e.g, 1234
output_folder: !ref results/<seed>
train_log: !ref <output_folder>/train_log.txt

# Data files
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Neural Parameters
number_of_epochs: 50
batch_size: 16
lr: 0.001
weight_decay: 0.0001
dropout_rate: 0.15
ctc_weight: 0.2
n_mels: 40

# CNN parameters
out_channels: 128
kernel_size: 3
pooling_size: 2
n_blocks: 2

# Decoding parameters
bos_index: 39
eos_index: 39
min_decode_ratio: 0.0
max_decode_ratio: 1.0
beam_size: 16
length_penalty: 0.2
eos_penalty: 1.5

device: 'cuda:0'

# Functions
rnn_enc: !speechbrain.nnet.RNN.RNN
    rnn_type: ligru
    n_neurons: 256
    nonlinearity: tanh
    num_layers: 4
    dropout: !ref <dropout_rate>
    bidirectional: True

rnn_dec: !speechbrain.nnet.RNN.AttentionalRNNDecoder
    rnn_type: gru
    attn_type: location
    n_neurons: 256
    attn_dim: 256
    attn_out_dim: 256
    vocab_dim: 40 # 39 phonemes + 1 bos
    emb_dim: 128
    num_layers: 1
    scaling: 1.0
    channels: 10
    kernel_size: 100
    bos_index: !ref <bos_index>

ctc_linear: !speechbrain.nnet.linear.Linear
    n_neurons: 40 # 39 phonemes + 1 blank

seq_linear: !speechbrain.nnet.linear.Linear
    n_neurons: 40 # 39 phonemes + 1 eos

softmax: !speechbrain.nnet.activations.Softmax
    apply_log: True

optimizer: !speechbrain.nnet.optimizers.Optimize
    optimizer_type: adam
    weight_decay: !ref <weight_decay>
    learning_rate: !ref <lr>

lr_annealing: !speechbrain.nnet.lr_scheduling.LRScheduler
    annealing_type: newbob
    N_epochs: !ref <number_of_epochs>
    lr_initial: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

normalize: !speechbrain.processing.features.InputNormalization
    norm_type: global

compute_features: !speechbrain.lobes.features.fbank.Fbank

epoch_counter: !speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

train_loader: !speechbrain.data_io.data_io.DataLoaderFactory
    &loader
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, phn]

valid_loader: !speechbrain.data_io.data_io.DataLoaderFactory
    <<: *loader
    csv_file: !ref <csv_valid>

test_loader: !speechbrain.data_io.data_io.DataLoaderFactory
    <<: *loader
    csv_file: !ref <csv_test>
    batch_size: !ref <batch_size>

ctc_cost: !speechbrain.nnet.losses.ComputeCost
    cost_type: ctc
    blank_index: 39

seq_cost: !speechbrain.nnet.losses.ComputeCost
    cost_type: nll
    eos_index: !ref <eos_index>
    append_eos: True
    label_smoothing: 0.1
