# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data files
data_folder: !PLACEHOLDER
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Neural Parameters
N_epochs: 10
N_batch: 1
lr: 0.002

# Model parameters
activation: !name:torch.nn.LeakyReLU
rnn_layers: 1
rnn_neurons: 128
rnn_bidirectional: True

# token infomation
bos: 42
eos: 42

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <N_batch>
    csv_read: [char, phn]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <N_batch>
    csv_read: [char, phn]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    csv_read: [char, phn]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

enc: !new:speechbrain.nnet.RNN.LSTM
    input_shape: [null, null, 128]
    bidirectional: True
    hidden_size: 64
    num_layers: 1
    dropout: 0.0

lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <rnn_neurons>
    n_neurons: 43  # 42 phonemes + 1 eos
    bias: False

encoder_emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: 28  # 27 chars + 1 bos
    embedding_dim: 128

emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: 43  # 42 phonemes + 1 bos
    embedding_dim: 128

dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: 128
    input_size: 128
    rnn_type: gru
    attn_type: content
    hidden_size: !ref <rnn_neurons>
    attn_dim: !ref <rnn_neurons>
    num_layers: 1

softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

modules:
    enc: !ref <enc>
    emb: !ref <emb>
    dec: !ref <dec>
    lin: !ref <lin>

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

searcher: !new:speechbrain.decoders.seq2seq.S2SRNNGreedySearcher
    embedding: !ref <emb>
    decoder: !ref <dec>
    linear: !ref <lin>
    bos_index: !ref <bos>
    eos_index: !ref <eos>
    min_decode_ratio: 0
    max_decode_ratio: 0.1

compute_cost: !name:speechbrain.nnet.losses.nll_loss

per_stats: !name:speechbrain.utils.metric_stats.ErrorRateStats
