# Seed needs to be set at top of yaml, before objects with parameters are made
# NOTE: Seed does not guarantee replicability with CTC
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
sample_rate: 16000
example_length: 2

# Data files
data_folder: ../../../../samples/speech_labelling
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/train.csv
csv_test: !ref <data_folder>/train.csv

# Neural Parameters
N_epochs: 10
N_batch: 2
lr: 0.01

# Model parameters
rnn_layers: 2
rnn_neurons: 256
emb_size: 23
dropout: 0.1

# Outputs
output_neurons: 1

compute_features: !new:speechbrain.lobes.features.mfcc.MFCC


mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

rnn: !new:speechbrain.nnet.RNN.LSTM
    hidden_size: !ref <rnn_neurons>
    num_layers: !ref <rnn_layers>
    dropout: !ref <dropout>
    bidirectional: False
    re_init: True
    return_hidden: False

lin: !new:speechbrain.nnet.linear.Linear
    n_neurons: !ref <output_neurons>
    bias: False

compute_BCE_cost: !name:speechbrain.nnet.losses.compute_masked_loss

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>
