# ############################################################################
# Model: WavLM + CTC
# Authors: Pooneh Mousavi 2022, Luca Della Libera 2022
# ############################################################################

seed: 1986
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data preparation
old_locales: [ pl, ar]
train_with_old_locales: True

new_locales: [ eo, kab, mhr, ckb, ab, kmr, fy-NL, ia]
download_dir: /gpfsscratch/rech/nou/uzn19yk/download/cv-corpus-12.0-2022-12-07/
max_durations:  [36000, 3600, 3600] #for whisper-large-v2

# Output directories
output_dir: !ref results/<wavlm_variant>/multilingual_ft/train_ft_rnn/<seed>
save_dir: !ref <output_dir>/save
save_folder: !ref <save_dir>

# Training parameters
train_batch_size: 8  # 32 for whisper-base, 1 for whisper-large-v2
valid_batch_size: 8  # 32 for whisper-base, 1 for whisper-large-v2
train_num_workers: 6
valid_num_workers: 6

sample_rate: 16000
sorting: ascending
avoid_if_longer_than: 8

ignore_index: -100  # For cross-entropy loss
label_smoothing: 0

num_epochs: 10
lr: 0.9
lr_wav2vec: 0.0001

improvement_threshold: 0.0025
annealing_factor: 0.8

activation: !name:torch.nn.LeakyReLU
dnn_layers: 1
dnn_neurons: 1024

output_neurons: 145  # Does not matter, it will be changed in the file
wavlm_variant: wavlm-large  # whisper-large-v2
wavlm_hub: /gpfsstore/rech/nou/uzn19yk/wavlm/
log_softmax: !new:speechbrain.nnet.activations.Softmax
   apply_log: True



auto_mix_prec: True  # True for whisper-large-v2 (for full dataset it causes NaN in forward pass for Kinyarwanda)
gradient_checkpointing: False
ckpt_interval_minutes: 15

forced_decoder_locale: null  # Set dynamically
normalize_transcripts: True

# Dataloader options
train_dataloader_kwargs:
    batch_size: !ref <train_batch_size>
    num_workers: !ref <train_num_workers>

valid_dataloader_kwargs:
    batch_size: !ref <valid_batch_size>
    num_workers: !ref <valid_num_workers>

# Modules

wavlm: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
   source: !ref <wavlm_hub>
   output_norm: True
   freeze_feature_extractor: True
   freeze: False
   save_path: !ref <save_folder>/wav2vec2_checkpoint

decoder: !new:speechbrain.nnet.RNN.LSTM
   input_shape: [Null, Null, 1024]
   num_layers: 2
   bidirectional : True
   dropout: 0.2
   hidden_size: 1024


ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
   blank_index: !ref <blank_index>

modules:
   wavlm: !ref <wavlm>
   decoder: !ref <decoder>
    
model: !new:torch.nn.ModuleList
   - [!ref <decoder>]


model_opt_class: !name:torch.optim.Adadelta
   lr: !ref <lr>
   rho: 0.95
   eps: 1.e-8

wav2vec_opt_class: !name:torch.optim.Adam
   lr: !ref <lr_wav2vec>

lr_annealing_model: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr>
   improvement_threshold: 0.0025
   annealing_factor: 0.8
   patient: 0

lr_annealing_wav2vec: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr_wav2vec>
   improvement_threshold: 0.0025
   annealing_factor: 0.9
   patient: 0

label_encoder: !new:speechbrain.dataio.encoder.CTCTextEncoder

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
   checkpoints_dir: !ref <save_folder>
   recoverables:
      wav2vec2: !ref <wavlm>
      model: !ref <model>
      scheduler_model: !ref <lr_annealing_model>
      scheduler_wav2vec: !ref <lr_annealing_wav2vec>
      counter: !ref <epoch_counter>
      tokenizer: !ref <label_encoder>
blank_index: 0
bos_index: 1
eos_index: 2




# Performance metrics
wer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True

# Counters, checkpointers, loggers, etc.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <num_epochs>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <output_dir>/train_log.txt
