# ################################
# Model: VGG2 + LiGRU with time pooling for efficiency
# Additions: TimeDomainSpecAugment
# Authors: Mirco Ravanelli & Peter Plantinga 2020
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/noisy_inputs/<seed>
cer_file: !ref <output_folder>/cer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
pretrained: clean_model.ckpt

# Data files
data_folder: !PLACEHOLDER  # e.g, /localscratch/noisy-vctk-16k/
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/valid.csv
csv_test: !ref <data_folder>/valid.csv
loaders: noisy_loaders

# Training parameters
number_of_epochs: 40
batch_size: 8
lr: 1.0
device: 'cuda:0'

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40

# Model parameters
activation: !name:torch.nn.LeakyReLU
dropout: 0.15
cnn_blocks: 2
cnn_channels: (128, 256)
cnn_kernelsize: (3, 3)
rnn_layers: 4
rnn_neurons: 512
rnn_bidirectional: True
dnn_blocks: 2
dnn_neurons: 512

# Outputs
output_neurons: 44
blank_index: !ref <output_neurons> - 1

normalize: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

clean_loaders:
    train: !new:speechbrain.data_io.DataLoaderFactory
        csv_file: !ref <csv_train>
        batch_size: !ref <batch_size>
        sentence_sorting: ascending
        output_folder: !ref <output_folder>
        csv_read: [clean_wav, char]
        avoid_if_longer_than: 10
    valid: !new:speechbrain.data_io.DataLoaderFactory
        csv_file: !ref <csv_valid>
        batch_size: !ref <batch_size>
        sentence_sorting: ascending
        output_folder: !ref <output_folder>
        csv_read: [clean_wav, char]
    test: !new:speechbrain.data_io.DataLoaderFactory
        csv_file: !ref <csv_test>
        batch_size: !ref <batch_size>
        sentence_sorting: ascending
        output_folder: !ref <output_folder>
        csv_read: [clean_wav, char]

noisy_loaders:
    train: !new:speechbrain.data_io.DataLoaderFactory
        csv_file: !ref <csv_train>
        batch_size: !ref <batch_size>
        sentence_sorting: ascending
        output_folder: !ref <output_folder>
        csv_read: [noisy_wav, char]
        avoid_if_longer_than: 10
    valid: !new:speechbrain.data_io.DataLoaderFactory
        csv_file: !ref <csv_valid>
        batch_size: !ref <batch_size>
        sentence_sorting: ascending
        output_folder: !ref <output_folder>
        csv_read: [noisy_wav, char]
    test: !new:speechbrain.data_io.DataLoaderFactory
        csv_file: !ref <csv_test>
        batch_size: !ref <batch_size>
        sentence_sorting: ascending
        output_folder: !ref <output_folder>
        csv_read: [noisy_wav, char]

model: !new:speechbrain.lobes.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !ref <activation>
    dropout: !ref <dropout>
    cnn_blocks: !ref <cnn_blocks>
    cnn_channels: !ref <cnn_channels>
    cnn_kernelsize: !ref <cnn_kernelsize>
    time_pooling: True
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    rnn_bidirectional: !ref <rnn_bidirectional>
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

output: !new:speechbrain.nnet.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: !ref <output_neurons>
    bias: False

jit_modules:
    model: !ref <model>

opt_class: !name:torch.optim.Adadelta
    lr: !ref <lr>
    rho: 0.95
    eps: 1.e-8

lr_annealing: !new:speechbrain.nnet.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

checkpointer: !new:speechbrain.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        output: !ref <output>
        scheduler: !ref <lr_annealing>
        normalizer: !ref <normalize>
        counter: !ref <epoch_counter>

hparams:
    cer_file: !ref <cer_file>
    loaders: !ref <loaders>
    output: !ref <output>
    lr_annealing: !ref <lr_annealing>
    normalize: !ref <normalize>
    epoch_counter: !ref <epoch_counter>
    log_softmax: !new:speechbrain.nnet.Softmax
        apply_log: True
    compute_cost: !name:speechbrain.nnet.ctc_loss
        blank_index: !ref <blank_index>
    train_logger: !new:speechbrain.FileTrainLogger
        save_file: !ref <train_log>
    augmentation: !new:speechbrain.lobes.TimeDomainSpecAugment
        sample_rate: !ref <sample_rate>
        speeds: [95, 100, 105]
    compute_features: !new:speechbrain.lobes.Fbank
        sample_rate: !ref <sample_rate>
        n_fft: !ref <n_fft>
        n_mels: !ref <n_mels>
    cer_computer: !name:speechbrain.ErrorRateStats
