###################################
# Experiment Parameters and setup #
###################################
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref ./results/hifi_gan/<seed>
save_folder: !ref <output_folder>/save
pretrained_path: !ref <save_folder>
train_log: !ref <output_folder>/train_log.txt
epochs: 500
keep_checkpoint_interval: 20

###################################
# Progress Samples                #
###################################
# Progress samples are used to monitor the progress
# of an ongoing training session by outputting samples
# of spectrograms, etc at regular intervals

# Whether to enable progress samples
progress_samples: True
# Whether to include incremental predictions in the samples
# Enabling them will cause a slowdown of the validation
# step
progress_samples_incremental: False
# The path where the samples will be stored
progress_sample_path: !ref <output_folder>/samples
# The interval, in epochs. For instance, if it is set to 5,
# progress samples will be output every 5 epochs
progress_samples_interval: 1
# The sample size for raw batch samples saved in batch.pth
# (useful mostly for model debugging)
progress_batch_sample_size: 2


#################################
# Data files and pre-processing #
#################################
data_folder: ./ #data_folder: !PLACEHOLDER # e.g, /localscratch/ljspeech
train_data_path: ../../../../../samples/dataset_samples/lj
# A path to a file with a list of IDs (one per line)
# listing the items from the main data set to be included
# in the training set
train_filter: null
valid_data_path: ../../../../../samples/dataset_samples/lj
# A path to a file with a list of IDs (one per line)
# listing the items from the main data set to be included
# in the validation set
valid_filter: null


################################
# Audio Parameters             #
################################
segment_size: 8192
sample_rate: 22050
hop_length: 256
win_length: 1024
n_mel_channels: 80
n_fft: 1024
n_stft: !ref <n_fft> // 2 + 1
mel_fmin: 0.0
mel_fmax: 8000.0
mel_normalized: null
power: 1
norm: "slaney"
mel_scale: "slaney"
dynamic_range_compression: True


################################
# Optimization Hyperparameters #
################################
learning_rate: 0.0002
weight_decay: 0.999
adam_b1: 0.8
adam_b2: 0.99
grad_clip_thresh: 1.0
batch_size: 16 #minimum 2


################################
# Model Parameters and model   #
################################

# generator params
in_channels: 80
out_channels: 1
resblock_type : "1"
resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
resblock_kernel_sizes: [3, 7, 11]
upsample_kernel_sizes: [16, 16, 4, 4]
upsample_initial_channel: 512
upsample_factors: [8, 8, 2, 2]
inference_padding: 5
cond_channels: 0
conv_pre_weight_norm: True
conv_post_weight_norm: True
conv_post_bias: True

#model
generator: !new:speechbrain.lobes.models.synthesis.hifi_gan.model.HifiganGenerator
    in_channels: !ref <in_channels>
    out_channels: !ref <out_channels>
    resblock_type : !ref <resblock_type>
    resblock_dilation_sizes: !ref <resblock_dilation_sizes>
    resblock_kernel_sizes: !ref <resblock_kernel_sizes>
    upsample_kernel_sizes: !ref <upsample_kernel_sizes>
    upsample_initial_channel: !ref <upsample_initial_channel>
    upsample_factors: !ref <upsample_factors>
    inference_padding: !ref <inference_padding>
    cond_channels: !ref <cond_channels>
    conv_pre_weight_norm: !ref <conv_pre_weight_norm>
    conv_post_weight_norm: !ref <conv_post_weight_norm>
    conv_post_bias: !ref <conv_post_bias>

discriminator: !new:speechbrain.lobes.models.synthesis.hifi_gan.model.HifiganDiscriminator

modules:
    generator: !ref <generator>
    discriminator: !ref <discriminator>

#generator loss
stft_loss: null
mseg_loss: !new:speechbrain.lobes.models.synthesis.hifi_gan.model.MSEGLoss
feat_match_loss: !new:speechbrain.lobes.models.synthesis.hifi_gan.model.MelganFeatureLoss
l1_spec_loss: !new:speechbrain.lobes.models.synthesis.hifi_gan.model.L1SpecLoss
    n_fft: !ref <n_fft>
    hop_length: !ref <hop_length>
    win_length: !ref <win_length>

generator_loss: !new:speechbrain.lobes.models.synthesis.hifi_gan.model.GeneratorLoss
    stft_loss: !ref <stft_loss>
    stft_loss_weight: 0
    mseg_loss: !ref <mseg_loss>
    mseg_loss_weight: 1
    feat_match_loss: !ref <feat_match_loss>
    feat_match_loss_weight: 108
    l1_spec_loss: !ref  <l1_spec_loss>
    l1_spec_loss_weight: 45

#discriminator loss
msed_loss: !new:speechbrain.lobes.models.synthesis.hifi_gan.model.MSEDLoss

discriminator_loss: !new:speechbrain.lobes.models.synthesis.hifi_gan.model.DiscriminatorLoss
    msed_loss: !ref <msed_loss>

#optimizer
opt_class_generator: !name:torch.optim.Adam
    lr: !ref <learning_rate>
    betas: [!ref <adam_b1>, !ref <adam_b2>]

opt_class_discriminator: !name:torch.optim.Adam
    lr: !ref <learning_rate>
    betas: [!ref <adam_b1>, !ref <adam_b2>]

#epoch object
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <epochs>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

#checkpointer
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        generator: !ref <generator>
        discriminator: !ref <discriminator>
        counter: !ref <epoch_counter>
        #scheduler: !ref <lr_annealing>

datasets:
    train:
        path: !ref <train_data_path>
        loader: !name:speechbrain.dataio.datasets.lj.load
        filter: !ref <train_filter>
    valid:
        path: !ref <valid_data_path>
        loader: !name:speechbrain.dataio.datasets.lj.load
        filter: !ref <valid_filter>

progress_sample_logger: !new:speechbrain.utils.progress_samples.ProgressSampleLogger
    output_path: !ref <progress_sample_path>
    batch_sample_size: !ref <progress_batch_sample_size>
    format_defs: 
            audio:
                extension: wav
                saver: !name:speechbrain.utils.progress_samples.save_audio
                kwargs:
                    sample_rate: !ref <sample_rate>
    formats:
        raw_batch: raw
        audio_source: audio
        audio_target: audio