# ################################
# Model: VGG2 + BLSTM + MLP
# Authors: Mirco Ravanelli
# ################################

number_of_epochs: 25
lr: 1.0

# Functions
model: !new:speechbrain.lobes.models.CRDNN.CRDNN
    cnn_blocks: 2
    dnn_blocks: 2

output: !new:speechbrain.nnet.linear.Linear
    n_neurons: 40
    bias: True

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

optimizer: !new:speechbrain.nnet.optimizers.Optimize
    optimizer_type: adadelta
    rho: 0.95
    learning_rate: !ref <lr>

lr_annealing: !new:speechbrain.nnet.lr_scheduling.LRScheduler
    annealing_type: newbob
    N_epochs: !ref <number_of_epochs>
    lr_initial: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

normalize: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

compute_features: !new:speechbrain.lobes.features.fbank.Fbank
