# Seed needs to be set at top of yaml, before objects with parameters are made
# NOTE: Seed does not guarantee replicability with CTC
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Neural Parameters
N_epochs: 15
batch_size: 1
lr: 0.002
blank_index: 0

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40

# Model parameters
activation: !name:torch.nn.LeakyReLU []
dropout: 0.15
cnn_blocks: 1
cnn_channels: (16,)
cnn_kernelsize: (3, 3)
rnn_layers: 1
rnn_neurons: 128
rnn_bidirectional: True
dnn_blocks: 1
dnn_neurons: 128

# Data:
data_folder: !PLACEHOLDER

label_encoder: !new:speechbrain.data_io.encoder.CTCTextEncoder

common_dynamic_items:
    phn_list:
        func: !name:speechbrain.utils.data_utils.split_by_whitespace
        argkeys: [phn]
    phn_encoded:
        func: !ref <label_encoder.encode_sequence_torch>
        argkeys: [phn_list]
    sig:
        func: !name:speechbrain.data_io.data_io.read_audio
        argkeys: [wav]
common_output_keys: ["id", "sig", "phn_encoded"]

train_data: !apply:speechbrain.data_io.dataset.DynamicItemDataset.from_json
    json_path: !ref <data_folder>/train.json
    replacements:
        data_root: !ref <data_folder>
    dynamic_items: !ref <common_dynamic_items>
    output_keys: !ref <common_output_keys>
train_loader: !new:speechbrain.data_io.dataloader.SaveableDataLoader
    dataset: !ref <train_data>
    batch_size: !ref <batch_size>

valid_data: !apply:speechbrain.data_io.dataset.DynamicItemDataset.from_json
    json_path: !ref <data_folder>/dev.json
    replacements:
        data_root: !ref <data_folder>
    dynamic_items: !ref <common_dynamic_items>
    output_keys: !ref <common_output_keys>
valid_loader: !new:speechbrain.data_io.dataloader.SaveableDataLoader
    dataset: !ref <valid_data>
    batch_size: !ref <batch_size>

#compute_features: !new:speechbrain.lobes.features.MFCC
compute_features: !new:speechbrain.lobes.features.Fbank
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    n_mels: !ref <n_mels>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

model: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !ref <activation>
    dropout: !ref <dropout>
    cnn_blocks: !ref <cnn_blocks>
    cnn_channels: !ref <cnn_channels>
    cnn_kernelsize: !ref <cnn_kernelsize>
    time_pooling: True
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    rnn_bidirectional: !ref <rnn_bidirectional>
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: 45  # 44 phonemes + 1 blank
    bias: False

softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

compute_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>

modules:
    model: !ref <model>
    lin: !ref <lin>
    mean_var_norm: !ref <mean_var_norm>

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

per_stats: !name:speechbrain.utils.metric_stats.ErrorRateStats
