# Seed needs to be set at top of yaml, before objects with parameters are made
# NOTE: Seed does not guarantee replicability with CTC
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]


# Neural Parameters
N_epochs: 10
N_batch: 2
lr: 0.004

# Model parameters
activation: !name:torch.nn.LeakyReLU
dropout: 0.0
cnn_blocks: 1
cnn_channels: (16,)
cnn_kernelsize: (3, 3)
rnn_layers: 1
rnn_neurons: 64
rnn_bidirectional: True
dnn_blocks: 1
dnn_neurons: 64

compute_features: !new:speechbrain.lobes.features.mfcc.MFCC

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

model: !new:speechbrain.lobes.CRDNN
    input_shape: [null, null, 660]
    activation: !ref <activation>
    dropout: !ref <dropout>
    cnn_blocks: !ref <cnn_blocks>
    cnn_channels: !ref <cnn_channels>
    cnn_kernelsize: !ref <cnn_kernelsize>
    time_pooling: True
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    rnn_bidirectional: !ref <rnn_bidirectional>
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

lin: !new:speechbrain.nnet.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: 45  # 44 phonemes + 1 blank
    bias: False

softmax: !new:speechbrain.nnet.Softmax
    apply_log: True

blank_index: 0
unknown_index: 1
compute_cost: !name:speechbrain.nnet.ctc_loss
    blank_index: !ref <blank_index>

modules:
    model: !ref <model>
    lin: !ref <lin>
    mean_var_norm: !ref <mean_var_norm>

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

per_stats: !name:speechbrain.ErrorRateStats
